### ISSUE TITLE
Unable to send additional args to 'clean-webpack-plugin'

### ISSUE THREAD

**Issue by ejwaibel** [neutrinojs/webpack-chain#104]
In my `vue.config.js` file, I have the following:
```
..
chainWebpack: config => {
    config
            .plugin('clean')
            .use('clean-webpack-plugin', [
                'css',
                'fonts',
                'images',
                'img',
                'js',
            ], { beforeEmit: true, root: path.join(__dirname, 'public') });
}
..
```

However, the additional arguments after the array of paths is not being picked up by webpackChain, you can see that from this inspect:
```
09:51 $ vue inspect --plugin clean
/* config.plugin('clean') */
new (require('clean-webpack-plugin'))(
  'css',
  'fonts',
  'images',
  'img',
  'js'
)
```

Is there something I'm missing so that the additional args get picked up?
```

**Comment by edmorley** [comment]
Hi! The second argument to `.use()` needs to be an array of the options to pass to the plugin, rather than there being more than two arguments passed to `.use()`.

eg:

```js
            .use('clean-webpack-plugin', [
              [
                'css',
                'fonts',
                'images',
                'img',
                'js',
              ],
              { beforeEmit: true, root: path.join(__dirname, 'public') }
            ]);
```

**Comment by ejwaibel** [comment]
Exactly what I was looking for! Thank you!

**Comment by edmorley** [comment]
You're welcome.

It's somewhat unfortunate that JS doesn't throw by default if too many arguments are passed, otherwise it would have made this much easier to spot.

@eliperelman what do you think about adding an explicit type check for args being an array here?
https://github.com/neutrinojs/webpack-chain/blob/3fe26f00c6b0ea7c8a481470934f719e8344e564/src/Plugin.js#L19-L21

...and also possibly a number of args check (since the array check wouldn't have caught this case, given the first argument passed was still an array, albeit not the right one)?
