### ISSUE TITLE
ChainedMap.entries() keys are not ordered

### ISSUE THREAD

**Issue by timkelty** [neutrinojs/webpack-chain#140]
Docs state:
> This will order properties by their name if the value is a ChainedMap that used .before() or .after()

However, this doesn't seem true (`.values()` and `.toConfig()` _do_ reflect the proper order, however):

```js
    neutrino.config.module
      .rule('two')
        .test(/two/)
        .end()
      .rule('one')
        .test(/one/)
        .before('two');

    // Bad: two, one
    console.log(neutrino.config.module.rules.entries());

    // Good: one, two
    console.log(neutrino.config.module.rules.values());
    console.log(neutrino.config.module.toConfig());
```

**Comment by yordis** [comment]
@timkelty question about this before I try to fix it.

Since `entries` is not an array but an object.

What do you mean by "order"?

That is the reason why we use `Map` since regular objects do not guarantee objects.

**Comment by timkelty** [comment]
@yordis yep, makes total sense…and looks like I just ended up using values in the end (https://github.com/neutrinojs/neutrino/pull/1276#issuecomment-455265909).

> That is the reason why we use Map since regular objects do not guarantee objects.

…but it appears`.entries` returns a plain object, not a `Map`.

At the very least, the docs make it sound like it will return an object with the keys ordered as specified, which it does not. (I know plain object key order isn't really guaranteed, but in practice it is…)

Is there any reason why `.entries` can't just return a `Map`?

**Comment by yordis** [comment]
>  Is there any reason why .entries can't just return a Map?

No really, unless people want to mess around with the internals that at least from this package perspective, we shouldn't do.

Since I am extracting some pieces out of this package, like the non-webpack stuff, there is definitely an added complexity to the existing code base that could be simplified.

But my fundamental question is about breaking changes, I can make a proposal.

I have a couple of suggestions and improvement to the package but it may cause some breaking changes, for example, I am working on #113 and I may know how to fix it but we can't use the existing code base without introducing some complexity that at least myself can't grasp.

So my question for your team is, are you fine with breaking changes?

As we speak I can take ownership of helping you with this package since it is becoming one of the main part of my toolkit so.

**Comment by timkelty** [comment]
> So my question for your team is, are you fine with breaking changes?

I don't see why not, as long as it is part of a major version bump. Ideally they could coincide with major bumps to Neutrino, but don't need to…

/cc @neutrinojs/core-contributors
