### ISSUE TITLE
how to modify externals

### ISSUE THREAD

**Issue by ziyi2** [neutrinojs/webpack-chain#142]
{ vue: { commonjs: 'vue', commonjs2: 'vue', root: 'Vue' } }

to

[ { vue: { commonjs: 'vue', commonjs2: 'vue', root: 'Vue' } },  function() {} ]

I don't know how to set.

**Comment by edmorley** [comment]
Hi! It sounds like you're having a problem configuring Vue's use of webpack-chain? If so, that is unfortunately out of scope for the issues section of this repository, since we don't have anything to do with the VueJS project, and issues are generally best for bugs/feature requests rather than tech support.

I'd recommend asking on https://forum.vuejs.org/ (and with more details, since there's not too much to go on with the details above).

Good luck! :-)
