### ISSUE TITLE
`Config.node` is incorrectly assumed to always be an object

### ISSUE THREAD

**Issue by opl-** [neutrinojs/webpack-chain#209]
webpack-chain [makes the incorrect assumption](https://github.com/neutrinojs/webpack-chain/blob/c59f853e7164f0acac9970c230a35500a1e5cbd3/src/Config.js#L122) that `Config.node` can never be anything other than an object, despite [webpack allowing it to be set to `false`](https://github.com/webpack/webpack.js.org/blob/f799227e966cc40aa90a1c0df975208608326f9b/src/content/configuration/node.md#node).

As a result, calling `config.set('node', false)` results in the value being lost and the `node` property not existing in the object generated with `Config.toConfig()`.

**Comment by edmorley** [comment]
Hi! Thank you for filing this issue - I agree webpack-chain should support this case. Would you be open to creating a PR for it? :-)

**Comment by SuperOleg39** [comment]
Hi! Try to fix this, have a little problem, if i want to add `config.node('value')` shortcut, because need a save backward compatibility, and can't make `config.node` callable and ChainedMap instance at the same time:

```
config.node('empty') // callable, need to be a function

config.node.set('global', false) // ChainedMap instance
```

It will be okay if i fix only `config.set('node', false)` case? But i don't know how user can save boolean value to node property, and them rewrite it to ChainedMap...

**Comment by SuperOleg39** [comment]
@edmorley Hello! If you have a time, need PR review)
