### ISSUE TITLE
Converting webpack-chain to TypeScript

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/webpack-chain#236]
Currently whilst webpack-chain does have TS type definitions, we frequently find bugs/omissions in the types, and to test these type definitions we have to have a significant amount of duplication in the form of the tests in `types/test/webpack-chain-tests.ts`.

Much of the JS (and in particular webpack) ecosystem is moving towards TypeScript, so I believe webpack-chain should just embrace it too.

I don't have much experience with migrating a codebase, so suggestions and PRs would be extremely useful.

I'm presuming we'd need to:
1. Add a build step to transpile back to JS in the published packages (run from `prepublish` I guess?).
2. Start migrating files, ideally incrementally

https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html

**Comment by yordis** [comment]
I already did some about this months ago, https://github.com/straw-hat-team/javascript/tree/develop/packages/libraries/chainable-config/src (this is agnostic of webpack-chain itself)

Worth sharing that I gave up to `this.extends` function since was really hard to add the typespec, so I ended up going for the verbose route.

If this implementation path is something that you are OK with, I can give you a hand since it is something familiar to me anyway.
