### ISSUE TITLE
Use webpack-chain to do webpack configuration in vue.config.js, so how to use speed-measure-webpack-plugin plugin?

### ISSUE THREAD

**Issue by geekskai** [neutrinojs/webpack-chain#261]
This is the configuration file of my vue-cli3

vue.config.js:

```
const CompressionWebpackPlugin = require('compression-webpack-plugin')
const SpeedMeasurePlugin = require("speed-measure-webpack-plugin");
const smp = new SpeedMeasurePlugin();

module.exports = {
  publicPath: './',
  lintOnSave: true, 
  chainWebpack(config) {
    config.devServer
      .port(8089)
      .open(true)
      .disableHostCheck(true)

    config.when(process.env.NODE_ENV !== 'development', config => {

      config  
        .plugin('gzip')
        .use(CompressionWebpackPlugin, [{
          algorithm: 'gzip',  
          test: new RegExp('\\.(' + ['js', 'css'].join('|') + ')$'),
          threshold: 8192,
          minRatio: 0.8,
          cache: true
        }])
    })
  }
}
```

**Comment by edmorley** [comment]
Hi! webpack-chain is an alternative way to generate webpack configs, and so in most cases is just a wrapper around webpack's existing options and behaviour. As such, any issues or questions are generally webpack questions, not webpack-chain specific, and so best to ask them in the webpack community or stack overflow, as it's not viable to provide general tech support here for everything related to webpack.

Also, since this is about Vue, please ask in the Vue community :-)
