### ISSUE TITLE
Is there a configure for packaging wasm file?

### ISSUE THREAD

**Issue by cathino** [neutrinojs/webpack-chain#323]
I know Webpack 5 support wasm,and my project based on vue3 + typescript + a wasm library,but I don't how config vue-cli to making webpack to packaging wasm file.

Could you show me a demo, please?
Thank you.

**Comment by edmorley** [comment]
Hi! webpack-chain is an alternative way to generate webpack configs, and so in most cases is just a wrapper around webpack's existing options and behaviour. As such, any issues or questions are generally webpack questions, not webpack-chain specific, and so best to ask them in the webpack community or stack overflow, as it's not viable to provide general tech support here for everything related to webpack.

Also, since this is about Vue, please ask in the Vue community :-)
